public namespace M.Tablas {
		   
		   public enum Columnas {
			   VIDEOJUEGOS_NOMBRE,
			   VIDEOJUEGOS_MOTOR,
			   VIDEOJUEGOS_DESARROLLADORA,
			   VIDEOJUEGOS_PUBLICADORA,
			   
			   DESARROLLADORAS_NOMBRE,
			   DESARROLLADORAS_SEDE,
			   DESARROLLADORAS_ACTIVO,
			   DESARROLLADORAS_FUNDACION,

			   PUBLICADORAS_NOMBRE,
			   PUBLICADORAS_SEDE,
			   PUBLICADORAS_ACTIVO,
			   PUBLICADORAS_FUNDACION,

			   CONSOLAS_NOMBRE,
			   CONSOLAS_FABRICANTE,
			   CONSOLAS_GENERACION,
			   CONSOLAS_CPU,
			   CONSOLAS_LANZAMIENTO
		   }
		   
}
